### ISSUE TITLE
Importing Certs in Ubuntu 16.04

### ISSUE THREAD

**Issue by kmf** [chef-cookbooks/trusted_certificate#12]
I'm using the cookbook on Ubuntu 16.04 ... is there a way I can check to see if the certs are installed correctly?

I'm having a issue the certs aren't being detected by the application I'm running.

Where does the cookbook place them by default?
Could I test the results using Inspec?

**Comment by qubitrenegade** [comment]
@kmf what application are you using (e.g. is it a Chef app as they come with their own cabundle, or is it a Java app because they use a different format ca...)?


>> Where does the cookbook place them by default?

Depending [on your platform](https://github.com/chef-cookbooks/trusted_certificate/blob/master/resources/trusted_certificate.rb#L55-L60) it will put your additional certs to be trusted in `/usr/local/share/ca-certificates` (debian) or `/etc/pki/ca-trust/source/anchors` RHEL.

Once that is complete `update-ca-trust` (RHEL) is executed which updates `/etc/pki/tls/certs/ca-bundle.crt` which is itself just a symlink to `/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem` (RHEL)

>> Could I test the results using Inspec?
Sure.  The way I test is with OpenSSL, this could be automated with inspec:

```
echo Q |openssl s_client -connect <yourhostname>:443 -CAfile /etc/pki/tls/certs/ca-bundle.crt -ign_eof 2>1 | grep 'Verify return code'
```

(The `echo Q |` is to force openssl to run "noninteractively" so it's not prompting for input.  OpenSSL likes to dump stuff to both STDOUT and STDERR which I'm sure there's a way to suppress, but I just dump STDERR to STDOUT, then the "Verify Return Code" should return 0 if the certificate is valid, it'll return 19 if it's self signed and there's a whole host of other error codes.)

Does that help?

**Comment by kmf** [comment]
Thanks for the Answer, I'll test it when I have time.
